package net.artemkv.referencewatches.service;

import net.artemkv.referencewatches.persistence.model.Brand;
import net.artemkv.referencewatches.persistence.repository.BrandRepository;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import javax.persistence.EntityManager;
import java.util.Optional;

@Service
public class DefaultBrandService implements BrandService {
    private final BrandRepository brandRepository;
    private final EntityManager entityManager;

    public DefaultBrandService(BrandRepository brandRepository, EntityManager entityManager) {
        this.brandRepository = brandRepository;
        this.entityManager = entityManager;
    }

    @Override
    public Page<Brand> getBrands(Pageable pageable) {
        return brandRepository.findAll(pageable);
    }

    @Override
    public Brand getBrand(long id) {
        return brandRepository.findById(id).orElse(null);
    }

    @Override
    @Transactional
    public Brand createBrand(Brand brand) {
        if (brand.getId() != 0) {
            throw new IllegalStateException("Id is generated by the database, should be empty.");
        }
        Brand brandCreated = brandRepository.save(brand);
        entityManager.refresh(brandCreated);
        return brandCreated;
    }

    @Override
    @Transactional
    public boolean updateBrand(Brand brand) {
        if (brand.getId() == 0) {
            throw new IllegalStateException("Id of existing entity should be provided.");
        }
        Optional<Brand> brandInDb = brandRepository.findById(brand.getId());
        if (!brandInDb.isPresent()) {
            return false;
        }
        brandRepository.save(brand);
        return true;
    }

    @Override
    @Transactional
    public boolean deleteBrand(long id) {
        Optional<Brand> brandInDb = brandRepository.findById(id);
        if (!brandInDb.isPresent()) {
            return false;
        }
        brandRepository.deleteById(id);
        return true;
    }
}
